Repository reactor/BlockHound, pull requests merged in 2019-10, with the labels that each got.

#53 hide BlockHoundRuntime from public API
  agent/src/main/java/reactor/blockhound/BlockHoundRuntime.java
  agent/src/main/java/reactor/blockhound/InstrumentationUtils.java
Labels: area/java-agent

#52 Javadoc
  agent/src/main/java/reactor/blockhound/BlockHound.java
  agent/src/main/java/reactor/blockhound/BlockingMethod.java
  agent/src/main/java/reactor/blockhound/integration/BlockHoundIntegration.java
Labels: type/documentation

#55 Hide `BlockHound`'s constructor
  agent/src/main/java/reactor/blockhound/BlockHound.java
Labels: area/java-agent, type/bug

#54 Simplify integrations after RC1 refactorings
  agent/src/main/java/reactor/blockhound/integration/ReactorIntegration.java
  agent/src/main/java/reactor/blockhound/integration/RxJava2Integration.java
  agent/src/main/java/reactor/blockhound/integration/util/TaskWrappingScheduledExecutorService.java
Labels: area/spi, type/enhancement

#56 Prepare Maven Central-friendly POM
  agent/build.gradle
  build.gradle
  gradle/publishing.gradle
  junit-platform/build.gradle
Labels: type/chore

#58 Reflect latest changes in the "How it works" docs
  docs/how_it_works.md
Labels: type/documentation

#60 Supported libraries section added to readme to resolve issue #44
  README.md
Labels: type/documentation

#61 Shading is the gift that keeps on giving
  agent/build.gradle
  agent/src/jarFileTest/java/reactor/blockhoud/AbstractJarFileTest.java
  agent/src/jarFileTest/java/reactor/blockhoud/JarFileShadingTest.java
Labels: area/java-agent, type/bug

#65 Throw specific BlockingOperationError instead of Error
  README.md
  agent/src/main/java/reactor/blockhound/BlockHound.java
  agent/src/main/java/reactor/blockhound/BlockingOperationError.java
  example/src/test/java/com/example/RxJavaTest.java
Labels: area/java-agent

#62 Hide BlockHound's own frame from the Error
  agent/src/main/java/reactor/blockhound/BlockHound.java
  example/src/test/java/com/example/StackTraceTest.java
Labels: area/java-agent, type/enhancement

#67 Use newly introduced `BlockingOperationError` in assertions
  agent/src/main/java/reactor/blockhound/BlockingOperationError.java
  example/build.gradle
  example/src/test/java/com/example/CustomBlockingMethodTest.java
  example/src/test/java/com/example/ReactorTest.java
Labels: type/chore

#68 Test with JDK13
  .github/workflows/ci.yml
  build.gradle
  example/build.gradle
Labels: type/chore
