Repository reactor/BlockHound, pull requests merged in 2019-03, with the labels that each got.

#12 Replace javassist instrumentation with ASM
  agent/build.gradle
  agent/src/main/java/reactor/ASMClassFileTransformer.java
  agent/src/main/java/reactor/BlockHound.java
  agent/src/main/java/reactor/BlockHoundRuntime.java
  agent/src/main/java/reactor/BlockingMethod.java
  example/build.gradle
Labels: type/housekeeping

#13 Integrate with JUnit Platform
  junit-platform/build.gradle
  junit-platform/src/main/java/reactor/blockhound/junit/platform/BlockHoundTestExecutionListener.java
  junit-platform/src/test/java/reactor/blockhound/junit/platform/JUnitPlatformDynamicIntegrationTest.java
  junit-platform/src/test/java/reactor/blockhound/junit/platform/JUnitPlatformIntegrationTest.java
  settings.gradle
Labels: type/enhancement

#16 Fixes the Windows binary name
  agent/build.gradle
Labels: type/bug

#17 Statically link mingw binaries for Windows build
  native-agent/CMakeLists.txt
Labels: type/enhancement

#18 Add a section to the docs about the testing frameworks
  docs/README.md
  docs/quick_start.md
  docs/test_frameworks_support.md
Labels: type/docs

#19 Improve wording in overview page
  docs/README.md
Labels: type/docs

#20 Improve wording in Testing Framwork Support
  docs/test_frameworks_support.md
Labels: type/docs
