Repository reactor/BlockHound, pull requests merged in 2023-01, with the labels that each got.

#312 Upgrade byte-buddy to version 1.12.21 for support of jdk 18+ versions
  README.md
  agent/build.gradle
  agent/src/main/java/reactor/blockhound/AllowancesByteBuddyTransformer.java
  agent/src/main/java/reactor/blockhound/BlockingCallsByteBuddyTransformer.java
  docs/quick_start.md
Labels: type/dependency-upgrade

#297 Add Premain-Class attribute
  agent/build.gradle
  agent/src/jarFileTest/java/reactor/blockhoud/JarFileShadingTest.java
  agent/src/main/java/reactor/blockhound/BlockHound.java
Labels: type/enhancement, for/user-attention

#323 Updated doc for -javaagent JVM option
  agent/src/main/java/reactor/blockhound/BlockHound.java
  docs/quick_start.md
Labels: type/documentation

#325 Added support for japicmp
  agent/build.gradle
  gradle.properties
Labels: type/enhancement

#326 Add uncaught exceptions to test method signature
  docs/tips.md
Labels: type/documentation

#153 Make BlockingMethod serializable
  agent/src/main/java/reactor/blockhound/BlockingMethod.java
Labels: type/enhancement

#327 BlockhoundIntegration SPI plugins ordering
  agent/src/main/java/reactor/blockhound/integration/BlockHoundIntegration.java
  example/src/test/java/com/example/IntegrationOrderingTest.java
  example/src/test/resources/META-INF/services/reactor.blockhound.integration.BlockHoundIntegration
Labels: type/bug, status/has-workaround

#328 Document how to use Blockhound from Tomcat webapp
  docs/quick_start.md
Labels: type/documentation

#329 Document how to disallow blocking calls inside allowed blocking calls
  docs/customization.md
  example/src/test/java/com/example/BlockingDisallowTest.java
Labels: type/documentation

#330 Reuse compatibleVersion project property in benchmark build.gradle
  benchmarks/build.gradle
Labels: type/enhancement
